# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"/\n\x0e\x41\x64\x64UserRequest\x12\x10\n\x08\x66ullName\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1f\n\x0c\x41\x64\x64UserReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x42\n\tCrmServer\x12\x35\n\x07\x41\x64\x64User\x12\x15.greet.AddUserRequest\x1a\x13.greet.AddUserReplyB\x10\xaa\x02\rCrmGrpcServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\rCrmGrpcServer'
  _globals['_ADDUSERREQUEST']._serialized_start=22
  _globals['_ADDUSERREQUEST']._serialized_end=69
  _globals['_ADDUSERREPLY']._serialized_start=71
  _globals['_ADDUSERREPLY']._serialized_end=102
  _globals['_CRMSERVER']._serialized_start=104
  _globals['_CRMSERVER']._serialized_end=170
# @@protoc_insertion_point(module_scope)
